/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.coursera.FinancialAid;

/**
 *
 * @author sanketkesarkar
 */
public class FinancialAidApplication extends javax.swing.JPanel {

    /**
     * Creates new form FinancialAidApplication
     */
    public FinancialAidApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFinancialRegistrationTitle = new javax.swing.JLabel();
        lblPersonalDetails = new javax.swing.JLabel();
        lblFinancialAidStudentName = new javax.swing.JLabel();
        lblFinancialAidStudentID = new javax.swing.JLabel();
        txtFinancialAidStudentName = new javax.swing.JTextField();
        txtFinancialAidStudentId = new javax.swing.JTextField();
        lblFinancialAidUsername = new javax.swing.JLabel();
        txtFinancialAidUsername = new javax.swing.JTextField();
        lblFinancialAidFinancialDetails = new javax.swing.JLabel();
        lblFinancialAidFamilyAnnualIncome = new javax.swing.JLabel();
        AnnualIncomejComboBox1 = new javax.swing.JComboBox<>();
        lblFinancialAidDetailedInformation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFinancialAidDetailedInformation = new javax.swing.JTextArea();
        lblFinancialAidCourseDetails = new javax.swing.JLabel();
        lblFinancialAidCourseName = new javax.swing.JLabel();
        txtFinancialAidCourseName = new javax.swing.JTextField();
        lblFinancialAidCourseId = new javax.swing.JLabel();
        txtFinancialAidCourseId = new javax.swing.JTextField();
        lblFinancialAidProfessor = new javax.swing.JLabel();
        txtFinancialAidProfessor = new javax.swing.JTextField();
        btnFinancialAidApply = new javax.swing.JButton();
        btnFinancialAidBack = new javax.swing.JButton();

        lblFinancialRegistrationTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblFinancialRegistrationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinancialRegistrationTitle.setText("FINANCIAL AID FORM");

        lblPersonalDetails.setText("PERSONAL DETAILS");

        lblFinancialAidStudentName.setText("Student Name:");

        lblFinancialAidStudentID.setText("Student ID:");

        lblFinancialAidUsername.setText("Username:");

        lblFinancialAidFinancialDetails.setText("FINANCIAL DETAILS");

        lblFinancialAidFamilyAnnualIncome.setText("Family Annual Income:");

        AnnualIncomejComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Low Income Group", "Middle Income Group", "Upper MIddle Income Group", "High Income Group", "Scholarship" }));

        lblFinancialAidDetailedInformation.setText("Detailed Information:");

        txtFinancialAidDetailedInformation.setColumns(20);
        txtFinancialAidDetailedInformation.setRows(5);
        jScrollPane1.setViewportView(txtFinancialAidDetailedInformation);

        lblFinancialAidCourseDetails.setText("COURSE DETAILS");

        lblFinancialAidCourseName.setText("Course Name:");

        lblFinancialAidCourseId.setText("Course ID:");

        lblFinancialAidProfessor.setText("Professor:");

        btnFinancialAidApply.setText("Apply");

        btnFinancialAidBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFinancialRegistrationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblPersonalDetails)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFinancialAidFinancialDetails)
                        .addComponent(lblFinancialAidCourseDetails)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblFinancialAidDetailedInformation)
                                .addComponent(lblFinancialAidFamilyAnnualIncome)
                                .addComponent(lblFinancialAidCourseName)
                                .addComponent(lblFinancialAidCourseId)
                                .addComponent(lblFinancialAidProfessor))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnFinancialAidApply)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFinancialAidBack))
                                .addComponent(AnnualIncomejComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(txtFinancialAidCourseName)
                                .addComponent(txtFinancialAidCourseId)
                                .addComponent(txtFinancialAidProfessor))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFinancialAidUsername)
                            .addComponent(lblFinancialAidStudentID)
                            .addComponent(lblFinancialAidStudentName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFinancialAidStudentName, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(txtFinancialAidStudentId)
                            .addComponent(txtFinancialAidUsername))))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFinancialRegistrationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPersonalDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinancialAidStudentName)
                    .addComponent(txtFinancialAidStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinancialAidStudentID)
                    .addComponent(txtFinancialAidStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinancialAidUsername)
                    .addComponent(txtFinancialAidUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFinancialAidCourseDetails)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinancialAidCourseName)
                    .addComponent(txtFinancialAidCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinancialAidCourseId)
                    .addComponent(txtFinancialAidCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinancialAidProfessor)
                    .addComponent(txtFinancialAidProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFinancialAidFinancialDetails)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinancialAidFamilyAnnualIncome)
                    .addComponent(AnnualIncomejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFinancialAidDetailedInformation)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinancialAidApply)
                    .addComponent(btnFinancialAidBack))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AnnualIncomejComboBox1;
    private javax.swing.JButton btnFinancialAidApply;
    private javax.swing.JButton btnFinancialAidBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFinancialAidCourseDetails;
    private javax.swing.JLabel lblFinancialAidCourseId;
    private javax.swing.JLabel lblFinancialAidCourseName;
    private javax.swing.JLabel lblFinancialAidDetailedInformation;
    private javax.swing.JLabel lblFinancialAidFamilyAnnualIncome;
    private javax.swing.JLabel lblFinancialAidFinancialDetails;
    private javax.swing.JLabel lblFinancialAidProfessor;
    private javax.swing.JLabel lblFinancialAidStudentID;
    private javax.swing.JLabel lblFinancialAidStudentName;
    private javax.swing.JLabel lblFinancialAidUsername;
    private javax.swing.JLabel lblFinancialRegistrationTitle;
    private javax.swing.JLabel lblPersonalDetails;
    private javax.swing.JTextField txtFinancialAidCourseId;
    private javax.swing.JTextField txtFinancialAidCourseName;
    private javax.swing.JTextArea txtFinancialAidDetailedInformation;
    private javax.swing.JTextField txtFinancialAidProfessor;
    private javax.swing.JTextField txtFinancialAidStudentId;
    private javax.swing.JTextField txtFinancialAidStudentName;
    private javax.swing.JTextField txtFinancialAidUsername;
    // End of variables declaration//GEN-END:variables
}
