/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.coursera.userinterface.authentication;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import main.java.com.coursera.usermanagement.UserList;
import main.java.com.coursera.users.Faculty;
import main.java.com.coursera.users.User;
import main.java.com.coursera.users.UserType;

/**
 *
 * @author sghar
 */
public class ProfessorRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorRegistrationJPanel
     */
    private javax.swing.JPanel CardSequencePanel;
    private User user;
    private UserList ulist;

    public ProfessorRegistrationJPanel(JPanel prjp, UserList ulist) {
        this.CardSequencePanel = prjp;
        initComponents();

        this.ulist = ulist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCreateProfessorSpecialization = new javax.swing.JTextField();
        lblTitleCreateProfessor = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblCreateProfessorSpecialization = new javax.swing.JLabel();
        cbExperience = new javax.swing.JComboBox<>();
        btnCreateProfessor = new javax.swing.JButton();
        lblCreateProfessorEmailId = new javax.swing.JLabel();
        btnProfessorBack = new javax.swing.JButton();
        lblExperience = new javax.swing.JLabel();
        lblCreateProfessorName = new javax.swing.JLabel();
        txtCreateProfessorName = new javax.swing.JTextField();
        lblCreateProfessorBloodGroup1 = new javax.swing.JLabel();
        txtCreateProfessorEmailId1 = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblCreateProfessorBloodGroup2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitleCreateProfessor.setBackground(new java.awt.Color(0, 0, 0));
        lblTitleCreateProfessor.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblTitleCreateProfessor.setForeground(new java.awt.Color(255, 51, 0));
        lblTitleCreateProfessor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleCreateProfessor.setText("CREATE PROFESSOR");
        lblTitleCreateProfessor.setOpaque(true);

        lblCreateProfessorSpecialization.setText("Professor Specialization:");

        cbExperience.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "2-5 years", "5-10 years", "10+ years", " " }));
        cbExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbExperienceActionPerformed(evt);
            }
        });

        btnCreateProfessor.setBackground(new java.awt.Color(204, 0, 0));
        btnCreateProfessor.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateProfessor.setText("CREATE");
        btnCreateProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProfessorActionPerformed(evt);
            }
        });

        lblCreateProfessorEmailId.setText("Professor Email ID:");

        btnProfessorBack.setBackground(new java.awt.Color(204, 0, 0));
        btnProfessorBack.setForeground(new java.awt.Color(255, 255, 255));
        btnProfessorBack.setText("BACK");
        btnProfessorBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorBackActionPerformed(evt);
            }
        });

        lblExperience.setText("Experience:");

        lblCreateProfessorName.setText("Professor Name:");

        lblCreateProfessorBloodGroup1.setText("Username:");

        lblCreateProfessorBloodGroup2.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 237, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblExperience)
                            .addComponent(lblCreateProfessorEmailId)
                            .addComponent(lblCreateProfessorSpecialization)
                            .addComponent(lblCreateProfessorName)
                            .addComponent(lblCreateProfessorBloodGroup1)
                            .addComponent(lblCreateProfessorBloodGroup2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreateProfessor)
                                .addGap(53, 53, 53)
                                .addComponent(btnProfessorBack))
                            .addComponent(txtCreateProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreateProfessorSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreateProfessorEmailId1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 250, Short.MAX_VALUE))
                    .addComponent(lblTitleCreateProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitleCreateProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateProfessorName)
                    .addComponent(txtCreateProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateProfessorSpecialization)
                    .addComponent(txtCreateProfessorSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateProfessorEmailId)
                    .addComponent(txtCreateProfessorEmailId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExperience)
                    .addComponent(cbExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateProfessorBloodGroup1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateProfessorBloodGroup2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateProfessor)
                    .addComponent(btnProfessorBack))
                .addContainerGap(381, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbExperienceActionPerformed
        // TODO add your handling code here:
        String exp = cbExperience.getSelectedItem().toString();
    }//GEN-LAST:event_cbExperienceActionPerformed

    private void btnCreateProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProfessorActionPerformed
        // TODO add your handling code here:

        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String email = txtCreateProfessorEmailId1.getText();
        String fullName = txtCreateProfessorName.getText();
        String specialization = txtCreateProfessorSpecialization.getText();
        String experience = cbExperience.getSelectedItem().toString();

        // Check if any of the required fields are empty
        if (username.isEmpty() || password.isEmpty() || email.isEmpty() || fullName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create a new user
        User newUser = new User(username, password, email, fullName, UserType.FACULTY);

        // Create a professor-specific instance (assuming UserType.PROFESSOR)
        Faculty faculty = new Faculty(username, password, email, fullName, UserType.FACULTY, specialization, experience);

        // Add the professor to the UserList (assuming ulist is a UserList instance)
        ulist.addUser(faculty);

        // Inform the user that the professor has been created
        JOptionPane.showMessageDialog(this, "Professor registration successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // You can add further handling for different user types (e.g., students) if needed.
        // Clear the form fields
        clearFormFields();

    }//GEN-LAST:event_btnCreateProfessorActionPerformed

    private void btnProfessorBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this); // Remove the current panel
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel); // Show the previous panel
    }//GEN-LAST:event_btnProfessorBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateProfessor;
    private javax.swing.JButton btnProfessorBack;
    private javax.swing.JComboBox<String> cbExperience;
    private javax.swing.JLabel lblCreateProfessorBloodGroup1;
    private javax.swing.JLabel lblCreateProfessorBloodGroup2;
    private javax.swing.JLabel lblCreateProfessorEmailId;
    private javax.swing.JLabel lblCreateProfessorName;
    private javax.swing.JLabel lblCreateProfessorSpecialization;
    private javax.swing.JLabel lblExperience;
    private javax.swing.JLabel lblTitleCreateProfessor;
    private javax.swing.JTextField txtCreateProfessorEmailId1;
    private javax.swing.JTextField txtCreateProfessorName;
    private javax.swing.JTextField txtCreateProfessorSpecialization;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void clearFormFields() {
        txtUsername.setText("");
        txtPassword.setText("");
        txtCreateProfessorEmailId1.setText("");
        txtCreateProfessorName.setText("");
        txtCreateProfessorSpecialization.setText("");
        cbExperience.setSelectedIndex(0); // Reset the combo box to the default selection
    }
}
