/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.coursera.userinterface.authentication;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import main.java.com.coursera.usermanagement.UserList;
import main.java.com.coursera.users.Faculty;
import main.java.com.coursera.users.Student;
import main.java.com.coursera.users.User;
import main.java.com.coursera.users.UserType;

/**
 *
 * @author sghar
 */
public class StudentRegistrationJPanel extends javax.swing.JPanel {

    private javax.swing.JPanel CardSequencePanel;
    private User user;
    private UserList ulist;

    /**
     * Creates new form StudentRegistrationJPanel
     * @param srjp
     * @param ulist
     */

    public StudentRegistrationJPanel(JPanel srjp, UserList ulist) {
        this.CardSequencePanel = srjp;
        initComponents();
        this.ulist = ulist;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStudentUsername = new javax.swing.JTextField();
        lblStudentUsername = new javax.swing.JLabel();
        txtStudentEmailID = new javax.swing.JTextField();
        cbStudentEducation = new javax.swing.JComboBox<>();
        txtStudentPassword = new javax.swing.JTextField();
        lblStudentPassword = new javax.swing.JLabel();
        btnCreateStudent = new javax.swing.JButton();
        lblStudentEmailId = new javax.swing.JLabel();
        btnStudentBack = new javax.swing.JButton();
        lblStudentEducation = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        lblTitleStudent = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();

        lblStudentUsername.setText("Username:");

        cbStudentEducation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Bachelor's Degree", "Master's Degree", "Doctoral Degree (Ph.D.)", "Professional Degree (e.g., MD, JD, MBA)", "Other" }));
        cbStudentEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStudentEducationActionPerformed(evt);
            }
        });

        lblStudentPassword.setText("Password:");

        btnCreateStudent.setText("CREATE");
        btnCreateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateStudentActionPerformed(evt);
            }
        });

        lblStudentEmailId.setText("Student Email ID:");

        btnStudentBack.setText("BACK");
        btnStudentBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentBackActionPerformed(evt);
            }
        });

        lblStudentEducation.setText("Highest level of Education:");

        lblStudentName.setText("Student Name:");

        lblTitleStudent.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblTitleStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleStudent.setText("CREATE STUDENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStudentEducation)
                    .addComponent(lblStudentEmailId)
                    .addComponent(lblStudentName)
                    .addComponent(lblStudentUsername)
                    .addComponent(lblStudentPassword))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStudentBack))
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStudentEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitleStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentEmailId)
                    .addComponent(txtStudentEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentEducation)
                    .addComponent(cbStudentEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentUsername)
                    .addComponent(txtStudentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentPassword)
                    .addComponent(txtStudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateStudent)
                    .addComponent(btnStudentBack))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbStudentEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStudentEducationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStudentEducationActionPerformed

    private void btnCreateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateStudentActionPerformed
        // TODO add your handling code here:
    String fullName = txtStudentName.getText();
    String email = txtStudentEmailID.getText();
    String education = (String) cbStudentEducation.getSelectedItem();
    String username = txtStudentUsername.getText();
    String password = txtStudentPassword.getText();
    
            // Check if any of the required fields are empty
        if (username.isEmpty() || password.isEmpty() || email.isEmpty() || fullName.isEmpty() || education.isEmpty() || "Select one".equals(education)) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create a new user
        User newUser = new User(username, password, email, fullName, UserType.STUDENT);

        // Create a professor-specific instance (assuming UserType.PROFESSOR)
        Student student = new Student(username, password, email, fullName, UserType.STUDENT, education);

        // Add the professor to the UserList (assuming ulist is a UserList instance)
        ulist.addUser(student);

        // Inform the user that the professor has been created
        JOptionPane.showMessageDialog(this, "Student registration successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // You can add further handling for different user types (e.g., students) if needed.
        // Clear the form fields
        clearFormFields();
    }//GEN-LAST:event_btnCreateStudentActionPerformed

    private void btnStudentBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentBackActionPerformed
        // TODO add your handling code here:
         CardSequencePanel.remove(this); // Remove the current panel
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel); // Show the previous panel
    }//GEN-LAST:event_btnStudentBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateStudent;
    private javax.swing.JButton btnStudentBack;
    private javax.swing.JComboBox<String> cbStudentEducation;
    private javax.swing.JLabel lblStudentEducation;
    private javax.swing.JLabel lblStudentEmailId;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentPassword;
    private javax.swing.JLabel lblStudentUsername;
    private javax.swing.JLabel lblTitleStudent;
    private javax.swing.JTextField txtStudentEmailID;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentPassword;
    private javax.swing.JTextField txtStudentUsername;
    // End of variables declaration//GEN-END:variables

    private void clearFormFields() {
    txtStudentName.setText("");
    txtStudentEmailID.setText("");
    cbStudentEducation.setSelectedItem("Select one");
    txtStudentUsername.setText("");
    txtStudentPassword.setText("");
}
}
