/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.coursera.userinterface.adminrole;

import javax.swing.JPanel;
import main.java.com.coursera.coursemanagement.CourseList;
import main.java.com.coursera.userinterface.authentication.ProfessorRegistrationJPanel;
import main.java.com.coursera.userinterface.authentication.StudentRegistrationJPanel;
import main.java.com.coursera.usermanagement.UserList;

/**
 *
 * @author sanketkesarkar
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    private javax.swing.JPanel CardSequencePanel;
    private UserList ulist;
    private CourseList clist;

    public AdminWorkAreaJPanel(JPanel awjp, UserList ulist, CourseList clist) {
        initComponents();
        
        this.CardSequencePanel = awjp;
        this.ulist = ulist; // Assign the ulist parameter to the class variable
        this.clist = clist;
        clist.printCourseList(clist);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdminCreateStudent = new javax.swing.JButton();
        btnAdminCreateProfessor = new javax.swing.JButton();
        lblAdminWorkAreaTitle = new javax.swing.JLabel();
        btnModifyStudent = new javax.swing.JButton();
        btnModifyProfessor = new javax.swing.JButton();

        btnAdminCreateStudent.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btnAdminCreateStudent.setText("Create Student");
        btnAdminCreateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCreateStudentActionPerformed(evt);
            }
        });

        btnAdminCreateProfessor.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btnAdminCreateProfessor.setText("Create Professor");
        btnAdminCreateProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCreateProfessorActionPerformed(evt);
            }
        });

        lblAdminWorkAreaTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblAdminWorkAreaTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminWorkAreaTitle.setText("ADMIN WORKAREA");

        btnModifyStudent.setText("Modify Student");
        btnModifyStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyStudentActionPerformed(evt);
            }
        });

        btnModifyProfessor.setText("Modify Professor");
        btnModifyProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdminWorkAreaTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdminCreateStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdminCreateProfessor))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModifyProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblAdminWorkAreaTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminCreateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminCreateProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminCreateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCreateStudentActionPerformed
        // TODO add your handling code here:
        StudentRegistrationJPanel studentRegistration;
        studentRegistration = new StudentRegistrationJPanel(CardSequencePanel, ulist);
        //CardSequencePanel.removeAll();
        CardSequencePanel.add("RegisterProfessor", studentRegistration);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnAdminCreateStudentActionPerformed

    private void btnModifyProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyProfessorActionPerformed
        // TODO add your handling code here:
        ModifyProfessorJPanel modifyProfessor;
        modifyProfessor = new ModifyProfessorJPanel(CardSequencePanel, ulist, clist);
        //CardSequencePanel.removeAll();
        CardSequencePanel.add("ModifyProfessor", modifyProfessor);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnModifyProfessorActionPerformed

    private void btnAdminCreateProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCreateProfessorActionPerformed
        // TODO add your handling code here:
        ProfessorRegistrationJPanel professorRegistration;
        professorRegistration = new ProfessorRegistrationJPanel(CardSequencePanel, ulist);
        //CardSequencePanel.removeAll();
        CardSequencePanel.add("AdminCreateProfessor", professorRegistration);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnAdminCreateProfessorActionPerformed

    private void btnModifyStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyStudentActionPerformed
        // TODO add your handling code here:
        ModifyStudentJPanel modifyStudent;
        modifyStudent = new ModifyStudentJPanel(CardSequencePanel, ulist, clist);
        //CardSequencePanel.removeAll();
        CardSequencePanel.add("ModifyStudent", modifyStudent);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnModifyStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminCreateProfessor;
    private javax.swing.JButton btnAdminCreateStudent;
    private javax.swing.JButton btnModifyProfessor;
    private javax.swing.JButton btnModifyStudent;
    private javax.swing.JLabel lblAdminWorkAreaTitle;
    // End of variables declaration//GEN-END:variables
}
