/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.coursera.userinterface.adminrole;

/**
 *
 * @author sanketkesarkar
 */
public class AdminCreateEmployer extends javax.swing.JPanel {

    /**
     * Creates new form AdminCreateEmployee
     */
    public AdminCreateEmployer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleCreateEmployee = new javax.swing.JLabel();
        lblCreateEmployeeName = new javax.swing.JLabel();
        lblCreateEmployeeID = new javax.swing.JLabel();
        lblCreateEmployeeType = new javax.swing.JLabel();
        lblCreateEmployeeDepartment = new javax.swing.JLabel();
        lblCreateEmployeeEmailId = new javax.swing.JLabel();
        lblCreateEmployeeBloodGroup = new javax.swing.JLabel();
        txtCreateEmployeeName = new javax.swing.JTextField();
        txtCreateEmployeeId = new javax.swing.JTextField();
        txtCreateEmployeeType = new javax.swing.JTextField();
        txtCreateEmployeeDepartment = new javax.swing.JTextField();
        txtCreateEmployeeEmailId = new javax.swing.JTextField();
        btnCreateEmployee = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cbEmployeeBloodGroup = new javax.swing.JComboBox<>();

        lblTitleCreateEmployee.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblTitleCreateEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleCreateEmployee.setText("CREATE EMPLOYEE");

        lblCreateEmployeeName.setText("Employee Name:");

        lblCreateEmployeeID.setText("Employee ID:");

        lblCreateEmployeeType.setText("Employee Type:");

        lblCreateEmployeeDepartment.setText("Employee Department:");

        lblCreateEmployeeEmailId.setText("Employee Email ID:");

        lblCreateEmployeeBloodGroup.setText("Employee Blood Group:");

        txtCreateEmployeeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateEmployeeTypeActionPerformed(evt);
            }
        });

        txtCreateEmployeeEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateEmployeeEmailIdActionPerformed(evt);
            }
        });

        btnCreateEmployee.setText("CREATE");

        btnBack.setText("BACK");

        cbEmployeeBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        cbEmployeeBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEmployeeBloodGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleCreateEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCreateEmployeeBloodGroup)
                    .addComponent(lblCreateEmployeeEmailId)
                    .addComponent(lblCreateEmployeeDepartment)
                    .addComponent(lblCreateEmployeeType)
                    .addComponent(lblCreateEmployeeName)
                    .addComponent(lblCreateEmployeeID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addComponent(txtCreateEmployeeName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtCreateEmployeeId, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtCreateEmployeeType, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtCreateEmployeeDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtCreateEmployeeEmailId, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(cbEmployeeBloodGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 465, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitleCreateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateEmployeeName)
                    .addComponent(txtCreateEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateEmployeeID)
                    .addComponent(txtCreateEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateEmployeeType)
                    .addComponent(txtCreateEmployeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateEmployeeDepartment)
                    .addComponent(txtCreateEmployeeDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateEmployeeEmailId)
                    .addComponent(txtCreateEmployeeEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateEmployeeBloodGroup)
                    .addComponent(cbEmployeeBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateEmployee)
                    .addComponent(btnBack))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCreateEmployeeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateEmployeeTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreateEmployeeTypeActionPerformed

    private void txtCreateEmployeeEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateEmployeeEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreateEmployeeEmailIdActionPerformed

    private void cbEmployeeBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEmployeeBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEmployeeBloodGroupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateEmployee;
    private javax.swing.JComboBox<String> cbEmployeeBloodGroup;
    private javax.swing.JLabel lblCreateEmployeeBloodGroup;
    private javax.swing.JLabel lblCreateEmployeeDepartment;
    private javax.swing.JLabel lblCreateEmployeeEmailId;
    private javax.swing.JLabel lblCreateEmployeeID;
    private javax.swing.JLabel lblCreateEmployeeName;
    private javax.swing.JLabel lblCreateEmployeeType;
    private javax.swing.JLabel lblTitleCreateEmployee;
    private javax.swing.JTextField txtCreateEmployeeDepartment;
    private javax.swing.JTextField txtCreateEmployeeEmailId;
    private javax.swing.JTextField txtCreateEmployeeId;
    private javax.swing.JTextField txtCreateEmployeeName;
    private javax.swing.JTextField txtCreateEmployeeType;
    // End of variables declaration//GEN-END:variables
}
