/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.coursera.userinterface.workareas.facultyrole;

import java.util.ArrayList;
import javax.swing.JPanel;
import main.java.com.coursera.auth.AuthManager;
import main.java.com.coursera.business.ProfessorRating;
import main.java.com.coursera.business.Rating;
import main.java.com.coursera.coursemanagement.CourseList;
import main.java.com.coursera.usermanagement.UserList;
import main.java.com.coursera.users.User;

/**
 *
 * @author sghar
 */
public class FacultyJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    private UserList ulist;
    private CourseList clist;
    private AuthManager authManager;
    private User loggedInUser;
    private int _professorId; // Add professorId variable

    /**
     * Creates new form FacultyWorkAreaJPanel
     *
     * @param fjp
     */
    public FacultyJPanel(JPanel fjp, CourseList courseList, UserList userList, AuthManager authManager, int professorId) {
        initComponents();
        this.CardSequencePanel = fjp;
        this.clist = courseList;
        this.ulist = userList;
        this.authManager = authManager;
        this._professorId = professorId; // Set the professorId

        // Populate employer ratings and comments
        populateEmployerRatingAndComments();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateCourse = new javax.swing.JButton();
        btnModifyCourse = new javax.swing.JButton();
        btnBacklog = new javax.swing.JButton();
        lblEmployerRate = new javax.swing.JLabel();
        txtEmployerRating = new javax.swing.JTextField();
        lblEmployerRate1 = new javax.swing.JLabel();
        txtEmployerComments = new javax.swing.JTextField();

        btnCreateCourse.setText("Create Course");
        btnCreateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCourseActionPerformed(evt);
            }
        });

        btnModifyCourse.setText("Modify Course");
        btnModifyCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyCourseActionPerformed(evt);
            }
        });

        btnBacklog.setText("<<Back");
        btnBacklog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacklogActionPerformed(evt);
            }
        });

        lblEmployerRate.setText("Employer Rating : ");

        lblEmployerRate1.setText("Employer Comments : ");

        txtEmployerComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployerCommentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBacklog)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblEmployerRate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmployerRating))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblEmployerRate1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmployerComments))
                            .addComponent(btnCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnModifyCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBacklog)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifyCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployerRate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployerRating, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployerRate1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployerComments, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCourseActionPerformed
        // TODO add your handling code here:
        CreateCourseJPanel createcourseJPanel;
        createcourseJPanel = new CreateCourseJPanel(CardSequencePanel, clist, ulist, authManager, _professorId);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("CreateCourse", createcourseJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnCreateCourseActionPerformed

    private void btnModifyCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyCourseActionPerformed
        // TODO add your handling code here:
        ModifyCourseJPanel modifycourseJPanel;
        modifycourseJPanel = new ModifyCourseJPanel(CardSequencePanel, clist, ulist, authManager, _professorId);
        CardSequencePanel.removeAll();
        CardSequencePanel.add("ModifyCourse", modifycourseJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnModifyCourseActionPerformed

    private void btnBacklogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacklogActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this); // Remove the current panel
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel); // Show the previous panel
    }//GEN-LAST:event_btnBacklogActionPerformed

    private void txtEmployerCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployerCommentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployerCommentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBacklog;
    private javax.swing.JButton btnCreateCourse;
    private javax.swing.JButton btnModifyCourse;
    private javax.swing.JLabel lblEmployerRate;
    private javax.swing.JLabel lblEmployerRate1;
    private javax.swing.JTextField txtEmployerComments;
    private javax.swing.JTextField txtEmployerRating;
    // End of variables declaration//GEN-END:variables

    private void populateEmployerRatingAndComments() {
        // Retrieve employer ratings and comments for the professor from the data model
        ProfessorRating professorRating = ProfessorRating.getInstance();
        ArrayList<Rating> employerRatings = professorRating.getEmployerRatings();

        // Find the ratings and comments for the professor based on their ID
        for (Rating rating : employerRatings) {
            if (rating.getProfessorId() == _professorId) {
                txtEmployerRating.setText(String.valueOf(rating.getRating())); // Populate the employer rating
                txtEmployerComments.setText(rating.getComments()); // Populate the employer comments
                break; // Once found, exit the loop
            }
        }
    }
}
