/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.coursera.userinterface.workareas.facultyrole;

/**
 *
 * @author sghar
 */
public class FacultyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyWorkAreaJPanel
     */
    public FacultyWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facultySplitPane = new javax.swing.JSplitPane();
        facultyMenuJPanel = new javax.swing.JPanel();
        btnCreateCourse = new javax.swing.JButton();
        btnModifyCourse = new javax.swing.JButton();
        btnScheduleCourse = new javax.swing.JButton();
        facultyContentAreaJPanel = new javax.swing.JPanel();

        btnCreateCourse.setText("Create Course");
        btnCreateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCourseActionPerformed(evt);
            }
        });

        btnModifyCourse.setText("Modify Course");
        btnModifyCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyCourseActionPerformed(evt);
            }
        });

        btnScheduleCourse.setText("Schedule Course");
        btnScheduleCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout facultyMenuJPanelLayout = new javax.swing.GroupLayout(facultyMenuJPanel);
        facultyMenuJPanel.setLayout(facultyMenuJPanelLayout);
        facultyMenuJPanelLayout.setHorizontalGroup(
            facultyMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyMenuJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facultyMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnScheduleCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifyCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        facultyMenuJPanelLayout.setVerticalGroup(
            facultyMenuJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyMenuJPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnCreateCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModifyCourse)
                .addGap(18, 18, 18)
                .addComponent(btnScheduleCourse)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        facultySplitPane.setLeftComponent(facultyMenuJPanel);

        javax.swing.GroupLayout facultyContentAreaJPanelLayout = new javax.swing.GroupLayout(facultyContentAreaJPanel);
        facultyContentAreaJPanel.setLayout(facultyContentAreaJPanelLayout);
        facultyContentAreaJPanelLayout.setHorizontalGroup(
            facultyContentAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        facultyContentAreaJPanelLayout.setVerticalGroup(
            facultyContentAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        facultySplitPane.setRightComponent(facultyContentAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facultySplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facultySplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCourseActionPerformed
        // TODO add your handling code here:
        CreateCourseJPanel createcourse = new CreateCourseJPanel();
        facultySplitPane.setRightComponent(createcourse);
    }//GEN-LAST:event_btnCreateCourseActionPerformed

    private void btnModifyCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyCourseActionPerformed
        // TODO add your handling code here:
        ModifyCourseJPanel modifycourse = new ModifyCourseJPanel();
        facultySplitPane.setRightComponent(modifycourse);
    }//GEN-LAST:event_btnModifyCourseActionPerformed

    private void btnScheduleCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleCourseActionPerformed
        // TODO add your handling code here:
        ScheduleCourseJPanel schedulecourse = new ScheduleCourseJPanel();
        facultySplitPane.setRightComponent(schedulecourse);
    }//GEN-LAST:event_btnScheduleCourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCourse;
    private javax.swing.JButton btnModifyCourse;
    private javax.swing.JButton btnScheduleCourse;
    private javax.swing.JPanel facultyContentAreaJPanel;
    private javax.swing.JPanel facultyMenuJPanel;
    private javax.swing.JSplitPane facultySplitPane;
    // End of variables declaration//GEN-END:variables
}
