/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.coursera.userinterface.workareas.StudentRole;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import main.java.com.coursera.auth.AuthManager;
import main.java.com.coursera.business.Course;
import main.java.com.coursera.coursemanagement.CourseList;
import main.java.com.coursera.usermanagement.UserList;
import main.java.com.coursera.users.User;

/**
 *
 * @author pradnyashinde
 */
public class GraduatedJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GraduatedJPanel
     */
    javax.swing.JPanel CardSequencePanel;
    private CourseList courseList;
    private int studentId;
    private String studentName;
     private UserList ulist;
    private User loggedInUser;
    private AuthManager authManager;
    public GraduatedJPanel(JPanel csp,User student,UserList userList, AuthManager authManager,CourseList courseList) {
        this.CardSequencePanel=csp;
        initComponents();
        this.courseList= courseList;
        this.ulist = userList;
        this.authManager = authManager;
        this.studentId = student.getUserID();
        //this.studentName = student.getUsername();
        txtStd.setText(String.valueOf(studentId));
        //txtStdName.setText(studentName);
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrad = new javax.swing.JTable();
        lblTranscript = new javax.swing.JLabel();
        lblStd = new javax.swing.JLabel();
        txtStd = new javax.swing.JTextField();
        lblStdName = new javax.swing.JLabel();
        txtStdName = new javax.swing.JTextField();
        btnBackCourse = new javax.swing.JButton();

        jLabel1.setText("Congratulations ! You have successfully completed all the courses required for graduation.");

        tblGrad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Course Id", "Course Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGrad);

        lblTranscript.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTranscript.setText("Transcript");

        lblStd.setText("Student Id:");

        txtStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStdActionPerformed(evt);
            }
        });

        lblStdName.setText("Student Name:");

        btnBackCourse.setText("<<Back");
        btnBackCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnBackCourse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStd)
                            .addComponent(txtStdName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStdName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(lblTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnBackCourse)
                .addGap(18, 18, 18)
                .addComponent(lblTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStdName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStdName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCourseActionPerformed
        // TODO add your handling code here:
        StudentJPanel panel=new StudentJPanel(CardSequencePanel, courseList, ulist, authManager);
        CardSequencePanel.add("StudentJPanel",panel);
        CardLayout layout=(CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
    }//GEN-LAST:event_btnBackCourseActionPerformed

    private void txtStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStd;
    private javax.swing.JLabel lblStdName;
    private javax.swing.JLabel lblTranscript;
    private javax.swing.JTable tblGrad;
    private javax.swing.JTextField txtStd;
    private javax.swing.JTextField txtStdName;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        int counter = 0;
        DefaultTableModel dtm=(DefaultTableModel) tblGrad.getModel();
        dtm.setRowCount(0);
        String student=String.valueOf(studentId);
        List<String> temp = new ArrayList<>();
        for(List<String> clist:courseList.nestedList){
            if(clist.get(0).equals(student)){
                temp.add(clist.get(1));
                  //temp.add(clist.get(2));
                  System.out.println(courseList.nestedList);
            }
        }
        for(Course c:courseList.getAllCourses()){
            
        
            for(String tmp: temp){
                
                if(Integer.toString(c.getCourseId()).equals(tmp))
                    
                
        
        {
            Object[] row=new Object[10];
            row[0]=++counter;
            row[1] = c.getCourseId();
            row[2]=c.getCourseName();
            dtm.addRow(row);
           
        }
                }
            }
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
